export:
  onnx:
    opset: 18                 # ONNX opset version; 17+ for recent PyTorch ops
    dynamic_axes: true        # Export with variable batch/sequence dims
  output_dir: "./exports"
  filenames:
    model: "model.onnx"
    quantized: "model.int8.onnx"
  metadata_paths:
    thresholds: "./configs/thresholds.json"
 # Tip: After export, use onnxruntime to sanity‑check a forward pass.
