export:
  onnx:
    opset: 18
    dynamic_axes: true
  output_dir: "./exports"
  filenames:
    model: "model.onnx"
    quantized: "model.int8.onnx"
  metadata_paths:
    thresholds: "./configs/thresholds.json"
