# Validation dataloader & transforms
val:
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std:  [0.229, 0.224, 0.225]
  image_size: 640
  patch_size: 16
  batch_size: 64
  num_workers: 8
  prefetch_factor: 2
  persistent_workers: true
