vocabulary:
  ignore_tags_file: "./configs/Tags_ignore.txt"  # Tags to always drop during vocab build
  min_frequency: 1                               # Keep tokens appearing ≥ this many times
  special_tokens:
    pad: "<PAD>"
    unk: "<UNK>"
  # Note: Special tokens are reserved; avoid collisions with real tags.
